package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSign;
import org.linlinjava.litemall.db.domain.LitemallSignExample;

public interface LitemallSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    long countByExample(LitemallSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int insert(LitemallSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSign selectOneByExample(LitemallSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSign selectOneByExampleSelective(@Param("example") LitemallSignExample example, @Param("selective") LitemallSign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallSign> selectByExampleSelective(@Param("example") LitemallSignExample example, @Param("selective") LitemallSign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    List<LitemallSign> selectByExample(LitemallSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSign selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    LitemallSign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSign record, @Param("example") LitemallSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSign record, @Param("example") LitemallSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSign record);
}