package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallIntegral;
import org.linlinjava.litemall.db.domain.LitemallIntegralExample;

public interface LitemallIntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    long countByExample(LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int insert(LitemallIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int insertSelective(LitemallIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegral selectOneByExample(LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegral selectOneByExampleSelective(@Param("example") LitemallIntegralExample example, @Param("selective") LitemallIntegral.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallIntegral> selectByExampleSelective(@Param("example") LitemallIntegralExample example, @Param("selective") LitemallIntegral.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    List<LitemallIntegral> selectByExample(LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegral selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallIntegral.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    LitemallIntegral selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegral selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallIntegral record, @Param("example") LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallIntegral record, @Param("example") LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}