spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root:  DEBUG
    org.springframework:  ERROR
    org.mybatis:  DEBUG
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  ERROR